# Exported from Render on 2025-05-20T09:58:21Z
services:
- type: web
  name: eproprietar-fe
  runtime: node
  repo: https://github.com/CzakoZoltan08/eproprietar-fe
  plan: free
  envVars:
  - key: NEXT_PUBLIC_STRIPE_PUBLIC_KEY
    sync: false
  - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    sync: false
  - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
    sync: false
  - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    sync: false
  - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
    sync: false
  - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    sync: false
  - key: NEXT_PUBLIC_FIREBASE_APP_ID
    sync: false
  - key: NEXT_PUBLIC_FIREBASE_API_KEY
    sync: false
  - key: NEXT_PUBLIC_API_URL
    sync: false
  - key: PORT
    sync: false
  region: oregon
  buildCommand: npm install --legacy-peer-deps; npm run build
  startCommand: npm run start
  autoDeployTrigger: commit
version: "1"
