export const QueryKeys = {
    PAGE: "page",
    LIMIT: "limit",
    FILTER_SURFACE: "filter.surface",
    FILTER_LAND_SURFACE: "filter.landSurface",
    FILTER_PRICE: "filter.price",
    FILTER_CITY: "filter.city",
    FILTER_COUNTY: "filter.county",
    FILTER_ROOMS: "filter.rooms",
    FILTER_ANNOUNCEMENT_TYPE: "filter.announcementType",
    FILTER_TRANSACTION_TYPE: "filter.transactionType",
    FILTER_USER: "filter.user",
    FILTER_STATUS: "filter.status",
    SEARCH: "search",
    FILTER_PROVIDER_TYPE: "filter.providerType",
};